spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ph8584777@gmail.com
    password: ijpp yzee dwpz chvu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  public:
    key: classpath:mynewpublickey.pem
  private:
    key: classpath:mynewkey-pkcs8.pem
