spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/kaliware
    username: root
    password: Kaliware@042
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
